/* Shared vocabulary for the CSS generators in this folder.
   Run `npm run gen` after editing. */

/** Every colour that gets a full set of component variants. */
export const COLORS = [
  'primary',
  'secondary',
  'success',
  'info',
  'warning',
  'danger',
  'light',
  'dark',
  'pop', // ja-ui extra — the hot pink / vivid yellow "confetti" colour
  'fresh', // ja-ui extra — mint / violet
];

/** Bootstrap's breakpoints, unchanged, so responsive infixes feel familiar. */
export const BREAKPOINTS = [
  ['', null],
  ['sm', '576px'],
  ['md', '768px'],
  ['lg', '992px'],
  ['xl', '1200px'],
  ['xxl', '1400px'],
];

export const infix = (bp) => (bp ? `-${bp}` : '');

export const banner = (title, note = '') =>
  `/* =============================================================================
   ja-ui — ${title}
   GENERATED by tools/${'gen'}-*.mjs — do not edit by hand; run \`npm run gen\`.${
     note ? `\n   ${note}` : ''
   }
   ============================================================================= */\n\n`;

/** Wrap a block of rules in a min-width media query (or return it bare). */
export const media = (min, body) => {
  if (!min) return body;
  const indented = body
    .trimEnd()
    .split('\n')
    .map((l) => (l ? `  ${l}` : ''))
    .join('\n');
  return `@media (width >= ${min}) {\n${indented}\n}\n`;
};
